- src/jobs/ios_build_and_test.yml
It just uses `project_type` param that was missing in `ios_build_and_test` job
| iOS     |    ✅     |
| Android |    ✅     |
> Use project_type in ios_build_and_test job

- src/commands/android_build.yml
Hi, I've started using this orb to automate mobile app testing. Thanks for your work! :smiley_cat: 
I'm still trying to get the orb to work, but meanwhile here's a quick and easy pull-request to contribute back, which just is a minor fix for the Android build gradle cache keys, such that the saved keys match the restored keys.
| iOS     |         |
| Android |    ✅     |
> update gradle cache keys to match on save and restore

- src/commands/setup_macos_executor.yml
FBSimulatorControl is no longer needed by detox and there is no need to install it. Moreover the specified commit does no longer work with the latest macos executor on circleci
fixes https://github.com/react-native-community/react-native-circleci-orb/issues/23
> remove FBSimulatorControl

- README.md
- src/examples/full.yml
- src/examples/ios.yml
- src/jobs/ios_build.yml
* Allow to just run the iOS Build without having the Detox lib in the project. Closes #29 
* How did you implement the solution?
I copied the `ios_build_and_test.yml` file and removed everything related to Detox.
* What areas of the library does it impact?
It adds a new job and do not change any existing job. 
Command used in the project:
Build the iOS app in release mode
```
- rn/ios_build:
name: build_ios_release
project_path: ios/OlistApp.xcodeproj
device: "iPhone X"
build_configuration: Release
scheme: OlistApp
requires:
- analyse_js
```
Running jobs: 
Some job configuration:
Result of build_ios job: 
Finished jobs:
-------
Commands used to deploy this project in a testing Orb (I was not able to test it locally, so I used my Orb in my current project to test this logic and its result …
> Add iOS build job and example of it

- CHANGELOG.md
- README.md
- package.json
- src/examples/full.yml
- src/examples/ios.yml
- src/jobs/android_build.yml
- src/jobs/android_test.yml
- src/jobs/ios_build.yml
- src/jobs/ios_build_and_test.yml
#25
I added the on_after_initialize before the yarn step. I think that it should be enough for most people
> possible fix for #25

- src/executors/linux_android.yml
Fixes gradle build daemon being killed in linux_android builds. Currently, Android builds may fail because the memory used by the build exceeds the memory available.
> fix: Define a max heap size for linux_android

- src/commands/setup_macos_executor.yml
fixes https://github.com/react-native-community/react-native-circleci-orb/issues/43
motivation: 
previously this was used to install node
```
echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
echo nvm install <<parameters.node_version>> >> $BASH_ENV
echo nvm alias default <<parameters.node_version>> >> $BASH_ENV
```
it ads `nvm install` to file at $BASH_ENV location. As described in https://linuxhint.com/bash-environment-variables/
> Value of this variable is expanded and used as the name of a startup file before a script is executed
so the `nvm install` script is executed for many (not all) commands user would type into terminal. This prints 
```v10.19.0 is already installed.
Now using node v10.19.0 (npm v6.13.4)
v10.19.0 …
```
> fix mac node install

- src/commands/ios_build.yml
- src/commands/pod_install.yml
- src/jobs/ios_build_and_test.yml
motivation: since RN 0.60 pods are default and it feels like it makes sense to have them covered. It's a short command, but circle has a cache for pod specs they recommend to use and this way users get it the right way for free.
I used `circleci config pack` to pack this orb and I'm using it with the proposed modifications in react-native-community/datetimepicker#144
| iOS     |    ✅❌     |
| Android |    ✅❌     |
> add pod install command

- src/commands/setup_macos_executor.yml
motivation: I needed to do this for https://github.com/react-native-community/datetimepicker/pull/155 to pass, the path was not right
https://github.com/react-native-community/datetimepicker/pull/155 passes
| iOS     |    ✅❌     |
| Android |    ✅❌     |
> fix: fix JAVA_HOME path

- src/commands/android_emulator_start.yml
- src/jobs/android_test.yml
motivation: the path to emulator used in the orb is not always the right one, this should fix it
this change is used in https://github.com/react-native-community/datetimepicker/pull/155
after some fighting, you see tests are passing
| iOS     |    ✅❌     |
| Android |    ✅❌     |
> fix: fix path to emulator

- src/commands/android_emulator_start.yml
this is potentially breaking because it removes google-services from the emulator - but I don't imagine people use those much (also considering that starting the emulator has been broken). This makes the command to follow emulator best practices collected by wix: https://github.com/wix/Detox/blob/master/docs/Introduction.AndroidEmulatorsBestPractices.md
used in https://github.com/react-native-community/datetimepicker/pull/155
| iOS     |    ✅❌     |
| Android |    ✅❌     |
> feat: follow emulator best practices

- src/jobs/android_test.yml
- src/jobs/ios_build_and_test.yml
This PR implements a param `store_artifact_path` to both `ios_build_test` and `android_test`, that let each job stores the artifacts created with Detox as CircleCI artifacts.
With these changes, I would be able to `zip` the screenshots created by Detox, and then move these files to the CircleCI artifact.
Sometimes it's interesting archiving Screenshots, Logs from E2E that can be used as regression tests. This PR let's specify on both jobs for testing an optional path to store these artifacts.
Just set an `ios_build_test` job following a config similar to this:
```yml
- react-native/ios_build_and_test:
checkout: true
store_artifact_path: /tmp/artifacts/
node_version: "10.17"
start_metro: true
project_type: workspace
scheme: Example
```
Passing these changes to a project, I was able to set …
> Adding possibility to store Detox artifacts on CircleCI

- src/commands/pod_install.yml
I had my own project commands, and then started to use RN orb commands instead. I noticed the increase of time taken in pod install job due to install without cache.
About implementation:
Two CircleCI commands: First I use the most recent cache generated, install pods and save changes based on podfile.lock and cache version
closes #58
| iOS     |    ✅     |
| Android |    ❌     |
> Add pod cache

- src/jobs/android_test.yml
```bash
#!/bin/bash -eo pipefail
circleci config pack src/ > packed-orb.yml
Error: Failed trying to marshal the tree to YAML : yaml: unmarshal errors:
line 50: mapping key "on_after_initialize" already defined at line 46
Exited with code exit status 255
```
`circleci config pack` was failing due to a duplicated parameter
> Fix orb pack command

- src/commands/setup_macos_executor.yml
I get this error in ci 
```
#!/bin/bash --login -eo pipefail
HOMEBREW_NO_AUTO_UPDATE=1 brew tap wix/brew >/dev/null
HOMEBREW_NO_AUTO_UPDATE=1 brew tap homebrew/cask >/dev/null
HOMEBREW_NO_AUTO_UPDATE=1 brew install applesimutils >/dev/null
HOMEBREW_NO_AUTO_UPDATE=1 brew cask install android-sdk >/dev/null
touch .watchmanconfig
node -v
v10.24.0 is already installed.
Now using node v10.24.0 (npm v6.14.11)
default -> 10 (-> v10.24.0 *)
v10.24.0 is already installed.
==> Tapping wix/brew
Cloning into '/usr/local/Homebrew/Library/Taps/wix/homebrew-brew'...
remote: Enumerating objects: 78, done.        
remote: Counting objects: 100% (78/78), done.        
remote: Compressing objects: 100% (44/44), done.        
remote: Total 622 (delta 41), reused 58 (delta 22), pack-reused 544 …
```
> Remove deprecated cask usage from brew install

- src/commands/pod_install.yml
The CircleCI spec repo cache was deprecated some time ago and whilst it is still up, has not been updated for a long time now. Eventually this will lead to failed pod installs where newer packages cannot be found in the repo.
Moving forward, we recommend the use of the Cocoapods CDN as it is significantly faster and more reliable than using the specs repo. The choice of using this will be down to the user to define in their Podfile.
References: 
https://circleci.com/docs/2.0/testing-ios/#optimizing-cocoapods
https://support.circleci.com/hc/en-us/articles/360045898974-Cocoapods-Spec-Repo-is-Outdated
> Remove deprecated CircleCI spec repo cache for pod install step

- src/commands/yarn_install.yml
- src/jobs/ios_build.yml
- src/jobs/ios_build_and_test.yml
Allow users to choose their own yarn caching folder, and let people try various strategies to resolve an open unarchiving issue https://github.com/react-native-community/react-native-circleci-orb/issues/66 (seemingly caused by changing this hard-coded path from one location to another [here](https://github.com/react-native-community/react-native-circleci-orb/pull/59)).
Defaults to the current path in `master` so this is a non-breaking change.
> Make yarn cache folder configurable

- src/jobs/android_test.yml
Add the ability to run commands after the emulator starts but before the detox tests run.
This will enable people to run common commands needed for UI automation, ex: https://testyour.app/blog/emulator
> Add optional command-running step after the emulator starts

- src/commands/setup_macos_executor.yml
closes #117 
I have been hitting the same error in RN date time picker
I'm not entirely sure why that folder should or should not be cached but I'm led to believe it should not be cached because
(1) it causes an error 😄  and not caching it makes CI pass
(2) it is not empty from the start, so untarring the archive attempts to overwrite something that existed before so I guess it could lead to inconsistencies or bugs like #117 
the `~/Library/Caches/Homebrew` folder is empty upon start so caching that one seems to make sense
> fix: do not cache /usr/local/Homebrew

- src/executors/linux_android.yml
This is needed so that the JDK options work, see:
https://discuss.circleci.com/t/unrecognized-vm-option-usecgroupmemorylimitforheap/37088
Related #120
This should be released as the final release in the current semver minor range I think, as suggested by @cortinico here
https://github.com/react-native-community/react-native-circleci-orb/issues/120#issuecomment-970220152
> fix(android): pin docker image to 4.2 for JDK8

- src/executors/linux_android.yml
See JDK8-->JDK11 migration notes here:
https://discuss.circleci.com/t/android-convenience-image-moving-to-java-v11-on-august-17th/36601/4
Related #120
BREAKING CHANGE: this orb is now officially using JDK11
> fix(android)!: use JDK11 compatible JVM options

- src/executors/linux_android.yml
The JVM options were coordinated with JDK8 + v4.x docker version pin earlier,
the JVM options were moved to JDK11 in #122 but the pin wasn't moved
They should be in sync with this
> fix(android): move docker android pin to JDK11 version

- src/commands/yarn_install.yml
Similar to `pod_install`'s `pod_install_directory` parameter, this adds a `yarn_install_directory` to `yarn_install`
Sometimes the `package.json` file isn't in the current/root directory so this option allows for project configurations where the `package.json` file is somewhere else
- Defaults to an empty string which will run as previously did `yarn install`
- Runs `yarn --cwd <<yarn_install_directory>>` if any non-empty string value is used
```yaml
- yarn_install:
yarn_install_directory: examples/oneOfMyExampleApps
cache_folder: ~/.cache/yarn
```
> yarn_install - add optional yarn_install_directory parameter

- src/commands/ios_simulator_start.yml
This is useful if you need to wait for the command to finish and simulator to boot before proceeding. Say for example you were running `xcrun simctl addmedia booted` without specifying `background: false` you would run into `No devices are booted` issue.
> Added background parameter to ios_simulator_start.yml

- README.md
- src/commands/ios_build.yml
- src/commands/ios_simulator_start.yml
- src/examples/full.yml
- src/examples/ios.yml
- src/jobs/ios_build.yml
- src/jobs/ios_build_and_test.yml
Xcode 13 by default no longer includes support for iPhone X out of the box. This PR replaces the default iOS device to iPhone 11.
> fix(ios): update default ios device to iPhone 11

- src/commands/android_build.yml
Fixes the `gradle` build cache key using for saving. It should [match the key used during restore](https://github.com/react-native-community/react-native-circleci-orb/blob/v6.2.1/src/commands/android_build.yml#L40-L43), otherwise there will never be a cache hit.
If the `build_type` needs to be taken into consideration, I can update the PR to:
```diff
diff --git a/src/commands/android_build.yml b/src/commands/android_build.yml
index 68bd274..befedfb 100644
--- a/src/commands/android_build.yml
+++ b/src/commands/android_build.yml
@@ -40,7 +40,7 @@ steps:
- restore_cache:
name: Restoring Gradle Build caches
keys:
-              - gradle-build-cache-{{ .Revision }}
+              - gradle-<<parameters.build_type>>-build-cache-{{ .Revision }}
- run:
name: Dispersing Gradle Build caches for …
```
> fix(android): fix gradle build cache key

- src/jobs/ios_build_and_test.yml
I was surprised that `pod install` wasn't happening. I expected it to default the directory to `ios`, since that's the most common arrangement. It makes sense to me to only `pod install` if `pod_install_directory` is set, but I had to look at the implementation to confirm that that's what it was doing. So this should make it clearer for the next person.
> Document that an empty `pod_install_directory` will skip `pod install`

- src/@orb.yml
Current the source code URL is part of the description and [not clickable](https://circleci.com/developer/orbs/orb/react-native-community/react-native?version=6.2.2):
With this PR the URL is gonna become more visible and clickable, akin to [`circleci/android`](https://circleci.com/developer/orbs/orb/circleci/android):
> Move the orb link to source_url

- src/commands/setup_macos_executor.yml
- src/jobs/android_test.yml
- src/jobs/ios_build.yml
- src/jobs/ios_build_and_test.yml
Currently setting up the `Detox Environment` takes over 7 mins:
The vast majority of the time is spent in `brew update`. With the introduction of `brew update` in #114 there is time penalty in every run. Unfortunately [CircleCI doesn't intent to update](https://ideas.circleci.com/images/p/run-brew-update-regularly-on-macos-images) the host machine regularly, which could alleviate the situation.
This PR is adding the ability to toggle `brew update`. The default remains to run `brew update` to avoid breaking changes.
> Add homebrew_update parameter to toggle brew update

- src/jobs/ios_build_and_test.yml
The cache parameter is already configured in the pod_install command.  
This just allows us to pass in the parameter from the parent job.
> Pass through pod cache from job to command

- src/jobs/android_test.yml
- src/jobs/ios_build_and_test.yml
> feat: allow passing executor parameters to test jobs

- src/commands/pod_install.yml
Currently there is no way to bust the `pod` cache since it falls back to the `cache-pods-` key:
This PR adds the missing `CACHE_VERSION` in the fallback key.
The fallback cache is preventing the upgrade of `react-native`, due to an error with `RTC-Folly` as described in https://github.com/facebook/react-native/pull/32659. In the meantime busting the cache would be a viable workaround.
- https://github.com/facebook/react-native/pull/32659
> fix: add missing CACHE_VERSION in pod_install

- src/commands/pod_install.yml
Quick follow up on #142 which [broke the build](https://app.circleci.com/pipelines/github/react-native-community/react-native-circleci-orb/306/workflows/43dc0cd5-8c99-46ea-84d4-adf41091f6d2/jobs/435).
Added single quotes around cache keys that start with special characters such as `{{`.
Fixes:
```sh
circleci config pack src/ > packed-orb.yml
Error: Failed trying to marshal the tree to YAML : yaml: line 22: did not find expected '-' indicator
```
Tested with:
```
➜  circleci config pack src > packed-orb.yml
➜  circleci orb validate packed-orb.yml
Orb at `packed-orb.yml` is valid.
```
Hopefully this does the trick. 🤞 Unfortunately I have no way to actually test it.
> fix: quote cache keys that start with special characters

- .circleci/config.yml
- src/executors/linux_js.yml
CircleCI deprecated the circleci/node image (see https://circleci.com/developer/images/image/cimg/node and https://circleci.com/docs/2.0/next-gen-migration-guide/). We're getting a warning on our CircleCI instance that there are going to be brownouts soon if you're still using these images, so I'm assuming it's good for everyone to get updated.
> chore: replace legacy circleci images

- .circleci/config.yml
- src/executors/linux_js.yml
BREAKING CHANGE: cimg/node doesn't support major Node version aliases the same way circleci/node did
> fix!: using supported Node version with cimg/node and updating comments

- .circleci/config.yml
- src/executors/linux_js.yml
Follow up to https://github.com/react-native-community/react-native-circleci-orb/pull/147. This removes the PATH to an old yarn version, which doesn't exist anymore with the current instance version.
This passed on our circleci instance so hopefully it's actually good now
> fix: yarn build issue with cimg/node

- src/commands/yarn_install.yml
Circle ci doesn't allow new line in the cache key anymore. This fixed `unexpected storage error` in my build.
> Fix yarn cache key - resolves #151

- src/commands/setup_macos_executor.yml
- src/commands/yarn_install.yml
Due to https://discuss.circleci.com/t/error-uploading-archive-cache-at-storage-caches/44222/3 the cache wasn't used on running CircleCI, but rather received an error as mentioned in https://github.com/react-native-community/react-native-circleci-orb/issues/151
The `key: |` was used in yarn + brew's cache.
> fix: 'an unexpected storage error occurred' on multiline keys

- README.md
Hi!
Having just looked into this repository for some CircleCI configuration, and (despite the helpful comment one line above) made the facepalm-worthy mistake of _not_ checking the latest version, I wanted to propose that the README be updated to reference the latest version of the orb. 
Thanks!
> Update README to reference the latest orb version

- src/executors/macos.yml
- src/jobs/android_test.yml
- src/jobs/ios_build.yml
- src/jobs/ios_build_and_test.yml
Xcode 12.4.0 has been removed from CircleCI
When we try to build with this orb we get the following error at the beginning
```
Build-agent version 1.0.134103-8a9e13ee (2022-08-02T13:24:16+0000)
Creating a dedicated VM with xcode:12.4.0 image
failed to create host: Image xcode:12.4.0 is not supported
failed to create host: Image xcode:12.4.0 is not supported
```
Sources:
https://discuss.circleci.com/t/xcode-image-deprecation/44294
https://circleci.com/docs/testing-ios#supported-xcode-versions
> Update XCode version to 12.5.1

- src/executors/linux_android.yml
- src/jobs/android_build.yml
Newer versions are needed for e.g. NodeJS updates.
Not changing the default to avoid breaking any builds.
> feat: allow specifying build image version for android build & executor

- src/executors/linux_android.yml
This time I actually ran `./scripts/pack.sh && circleci orb validate packed-orb.yml`. Would be nice if CI did that on PRs
> fix: yaml parsing build_image_version default as double

- README.md
Fix the orb badge in the README.
Going from this:
To this:
* https://discuss.circleci.com/t/new-orb-version-badge-endpoint/39515
> chore: fix orb badge

- .circleci/test-deploy.yml
- README.md
Rename the `master` branch to `main`.
Needs to be merged after the default branch is changed in the settings:
> chore: rename master branch to main

- .releaserc
Quick follow up to #188.
Fixes the [following error](https://app.circleci.com/pipelines/github/react-native-community/react-native-circleci-orb/394/workflows/deec3930-bd2a-4059-a063-d862d66e9002/jobs/770/parallel-runs/0/steps/0-108) in CircleCI:
> Specify main branch for semantic release

- src/commands/pod_install.yml
Allow a custom pod install command. Would allow executing with `bundle exec pod install` instead
> feat: support a custom pod install command

- src/commands/ios_build.yml
If scheme name has `-` build fails with the following error:
```
xcodebuild: error: Unknown build action '-'.
```
This should prevent this error from happening. Xcode allows to use those characters in scheme name. It's only bash issue.
I tried using `''` in config:
```
- rn/ios_build:
scheme: 'Schema Name - BDD'
```
it didn't help.
> fix: allow to use scheme with spaces and special characters
